### ISSUE TITLE
Can imputation of X, W before cross-fitting induce bias or overconfidence?

### ISSUE THREAD

**Issue by dsteinberg** [py-why/EconML#664]
Thank you all for such a wonderful library!

I'm concerned that imputing missing at random (MAR) entries in X and W outside of the cross-fitting procedures of the estimators in this library can induce bias, or at least over-confidence in results.

For example, if there is correlation between the missing values and other values in X and/or W, ideally we would want to only estimate these missing values from data *within* the current training/cross fit fold, otherwise we may have information leaking between folds.

At the moment this library requires us to impute missing data *before* the cross-fitting procedure (as far as I can tell). Should this requirement be relaxed to allow fitting of missing data later in the pipeline? Is this really a concern like I think it is?

For example, we can make estimators of the form,

```
est = make_pipeline(
    SimpleImputer(),
    Ridge()
)
```

using scikit-learn, but this library will not allow the propagation of `NaNs` to this estimator (I suppose we could use other values, but this seems brittle) because of checks like this:

https://github.com/microsoft/EconML/blob/7dd7683c987018511a07318b6f4b165018373aad/econml/utilities.py#L544

I think it would be easy to fix this issue. For example, we could propagate the `check_input` argument from the base classes to the relevant subclasses, e.g.:

https://github.com/microsoft/EconML/blob/7dd7683c987018511a07318b6f4b165018373aad/econml/_ortho_learner.py#L548

Or, we could remove input checking from this library (where appropriate) and allow the underlying scikit-learn estimators to fulfill this function for us.

The later approach seems like a better design to me since valid scikit-learn estimators have to check their input anyway, and so the input checking in this library is unnecessary repetition (remember - DRY).

(related issue: https://github.com/microsoft/EconML/issues/414)

**Comment by strayMat** [comment]
I am just realizing that this library opens the door of nan leakage between folds. Coming from the healthcare field, where NaN are present everywhere, this appears to me as a problematic issue. 

I would also be in favor of PR which would remove the input checking from econml and let sklearn do the input checking.

**Comment by fverac** [comment]
We currently have a PR in progress to enable missing values for W. Enabling missing values in X is less clear, see message from a discussion in our Discord.

> I agree that it would be reasonable for us to address this, but note that for many of our estimators this would really only work for W and not for X (e.g. for LinearDML, our second stage model is running a regression of Y_res on (T_res cross X), so any NaNs in X will be a problem even if the first stage model handles them without issue).
