### ISSUE TITLE
Causal Analysis Issue

### ISSUE THREAD

**Issue by Leo-T-Zang** [py-why/EconML#754]
Hi,

When using Causal Analysis Function, I encounter following warnings.

```
Function delayed is deprecated; The function `delayed` has been moved from `sklearn.utils.fixes` to `sklearn.utils.parallel`. This import path will be removed in 1.5.
`sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
`sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
Function delayed is deprecated; The function `delayed` has been moved from `sklearn.utils.fixes` to `sklearn.utils.parallel`. This import path will be removed in 1.5.
`sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
`sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
Trying to unpickle estimator OneHotEncoder from version 1.1.3 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
```

**Comment by Leo-T-Zang** [comment]
Follow-up questions:
1. What is the model or algorithm behind Cuasal Analysis Function to compute causal effect?
2. When the feature is numerical, how to compute causal effect?
    Specifically, my understanding to compute causal effect is based on categorical features. For example, when you flip 0 to 1 or 
    1 to 0, you manage to predict counterfactual situation. So what is counterfactual of continuous features and how to compute   
    it?

**Comment by Leo-T-Zang** [comment]
Thank you for your explanation. It helps a lot!

For problem 2, maybe my question is unclear. For example DML Model, if treatment is continouse, how to move around the treatment value and decide the slope (causal effect)?

**Comment by kbattocchi** [comment]
Sorry for the slow response.  Could you provide a full stack trace (and ideally a self-contained repro)?  It's possible we have a bug here but it's hard to know without understanding more of your context.

**Comment by Leo-T-Zang** [comment]
Problem is sovled. Thank you.
