### ISSUE TITLE
Behavior with Discrete Treatments (discrete_treatment=True)

### ISSUE THREAD

**Issue by marja-w** [py-why/EconML#787]
Hello,

I have a dataset with 10 different treatment arms and this is my code:

```
est = CausalForestDML(discrete_treatment=True)
est.fit(Y=Y, T=T, X=X, W=None)
```

T is the treatment column with 10 different values (A,B,C,D,E,F,G,H,I,J). 

When I compute the CATE from my test data set:

```
est.const_marginal_ate(X_test)
```

I assumed I would receive a CATE estimation for each treatment, but the array is only of length 9. 

Also, if I compute SHAP values

```
import shap
shap_values = est.shap_values(X)
```

The resulting dictionary `shap_values[name_of_outcome_variable]` only has 9 keys as well, missing the key `'treatment_code_A'`.

What did I do wrong? In general, how does the library handle multiple treatments?

**Comment by kbattocchi** [comment]
This is the expected behavior - for `effect`, you can pass any starting and ending treatment and we will give the effect of moving from one to the other; internally we compute this by (without loss of generality) treating a single treatment as a "control" and computing the marginal effects of moving from that treatment to each other one.

**Comment by marja-w** [comment]
Thank you @kbattocchi for the fast answer. I am not sure what exactly you mean by passing a starting and ending treatment for `effect`. Do you mean it as in passing in a variable of a provided function?

If I understood correctly, the CATE estimation results in 9 values, with each representing the CATE of moving from one, for example `treatment_code_A`, to another `treatment_code_B`, then the second value representing the CATE of moving from `treatment_code_B` to `treatment_code_C`, and so on. Or is `treatment_code_A` seen as control group, and all CATEs are computed outgoing from it, what would explain why it is not a key in the `shap_values` dictionary?

When the effect from moving from one treatment to the other is computed, are the examples labeled with other treatments ignored?
