### ISSUE TITLE
Background Variable for Causal Analysis Object

### ISSUE THREAD

**Issue by Leo-T-Zang** [py-why/EconML#792]
Hi,

I am using Object Causal Analysis and I wonder if there is a way to incorprate **background variables** for this call.

```
econml.solutions.causal_analysis.CausalAnalysis(feature_inds, categorical, heterogeneity_inds=None, 
feature_names=None, classification=False, 
upper_bound_on_cat_expansion=5, nuisance_models='linear', 
heterogeneity_model='linear', *, categories='auto', 
n_jobs=- 1, verbose=0, cv=5, mc_iters=3, 
skip_cat_limit_checks=False, random_state=None)
```
Say if I have multiple features as input and among them some are  background variable that I want to model has causal effect controled on them. What should I do in this case?

Thank you.

**Comment by kbattocchi** [comment]
If I understand your question correctly, this is already handled for you automatically - when you pass in a dataset, we consider each feature in `feature_inds` one-by-one to determine its direct causal effect on the outcome, and when we do this, we treat every other column in your array/dataframe (whether or not it also appears somewhere in the `feature_inds` list) as a control.

**Comment by Leo-T-Zang** [comment]
Thanks!
