### ISSUE TITLE
Scaling Othrolearners using Ray 

### ISSUE THREAD

**Issue by v-shaal** [py-why/EconML#793]
Currently its challenging to scale Ortholearners for a large dataset as via current implementation of `_crossfit`  is sequential which may not be efficient for large datapoints.
To over come this we can use Ray Remote function (Ray Tasks)  for remote and asynchronous invocations of each of the K folds simultaneously on separate Python workers.

This can be done via simply modifying the _crossfit in `_ortho_learner.py`.  
We conducted a performance analysis of the EconML implementation of DML and our version of DML_Ray at varying scales (10k, 100k, and 1Million) of treated units and using approximately 500 covariates generated by a synthetic data generator API sourced from  https://github.com/py-why/dowhy/blob/main/dowhy/datasets.py

Here's the link of the Implementation of DML scaled via Ray that I have created. Let me know your thoughts .
@amit-sharma @emrekiciman 

https://gist.github.com/vishal-d11/cd886eb6bdff96ad5a04711cb18339ed#file-dml_ray-ipynb

**Comment by fverac** [comment]
Thanks for sharing. Would you be able to share your findings from the performance analysis?

**Comment by v-shaal** [comment]
@fverac  yes we have done the performance analysis , we were able to run 1M units with about 500 covariates in ~7-8 Minutes over ray based implementation vs more than ~40min on current implementation on EC2-High Mem Node
<img width="391" alt="Screenshot 2023-07-21 at 1 03 31 PM" src="https://github.com/py-why/EconML/assets/17809096/1b96f155-9ba8-495e-b265-b505ec6a150b">

**Comment by vsyrgkanis** [comment]
This is a great achievement @v-shaal ! I think if there is a way to seamlessly incorporate this Ray Remote function framework, we should strongly consider it!

Do you know what it would take to incorporate in the library? Would you be willing to submit a PR with this improvement?

**Comment by v-shaal** [comment]
@fverac  @vsyrgkanis , I would be glad to work on this and raise a PR. I am currently going over the current structuring to figure out the best possible way to incorporate this with minimal changes to existing code structuring. let me know if you guys have any suggestions.

**Comment by v-shaal** [comment]
@vsyrgkanis  can you please assign this to me.

**Comment by v-shaal** [comment]
@vsyrgkanis @fverac @kbattocchi  , I've raised [PR](https://github.com/py-why/EconML/pull/800) for this , let me know the feedback
