### ISSUE TITLE
Only one CATE value is recorded from EconML (when called from DoWhy)

### ISSUE THREAD

**Issue by fverac** [py-why/EconML#795]
Supposedly CATE values are not the appropriate shape when calling EconML from dowhy >0.9. May not be a problem with EconML, but worth keeping on our radar.

https://github.com/py-why/dowhy/issues/890

**Comment by amit-sharma** [comment]
Ah, just checked. Looks like they did not specify any effect modifiers when providing the dataset to DoWhy.  Responded on [that issue](https://github.com/py-why/dowhy/issues/890#issuecomment-1646822828).
