### ISSUE TITLE
CausalForestDML need X to successfully run

### ISSUE THREAD

**Issue by xiaogangzhu** [py-why/EconML#802]
How can I fit a CausalForestDML to get the ATE without providing X?

**Comment by kbattocchi** [comment]
The point of CausalForestDML is to fit a forest on X, which isn't possible X is None.  So if all you want to do is compute an ATE, then just use LinearDML with X=None instead.

On the other hand, if you use CausalForestDML to compute a conditional average treatment effect (conditional on some actual variables in X), then that class provides both an `ate_` attribute which has a doubly-robust estimation of the ATE on the training data as well as `ate`, `ate_inference`, and `ate_interval` methods which will estimate the ATE, confidence intervals, etc. on some other population of Xs by averaging the estimated CATE over them.

**Comment by xiaogangzhu** [comment]
Thanks!
