### ISSUE TITLE
Changing covariance logic in DRIV

### ISSUE THREAD

**Issue by vsyrgkanis** [py-why/EconML#809]
When we do nuisance fitting in DRIV and calculating the conditional covariance beta=E[Tres*Zres|X], when the instrument is the projected treatment, i.e. E[T|Z,X], then this covariance is simply Var(E[T|Z,X] | X)

https://github.com/py-why/EconML/blob/de4f05d95c59b39275a7f2780bcfe4ef20aa1b47/econml/iv/dr/_dr.py#L74

So maybe one should use an alternative logic here, were we pass a _model_var that regresses (Tproj - Tpred)^2 on X to calculate the variance. It's still a bit problematic that we don't do internal nested sample splitting to calculate Tproj-Tpred. For instance, if you have overfitting models, then E[T|Z, X] and E[T|X], will both be perfectly predicting (artificially) the treatment T and the residual Tproj - Tpred will be artificially zero! So this seems a potentially bad design too. Maybe at this point one should be doing some simple nested cross-fitting.

Already we are re-using Tproj within sample, to calculate the target T* Tproj. In this case, for overfitting models, we will be artificially thinking that T and Tproj are highly correlated, because E[T|Z,X] will be perfectly predicting T and we will be ending up calculating Var(T|X) as a nuisance, instead of Var(E[T|Z,X]), thereby having a positive bias in our estimate of beta.

Switching the design to eliciting a var_z_x model instead of a tz_x model, will also remove the peculiarity in the API, where if T and Z are binary, then model_tz_x is expected to be a classifier if proj=False, but is expected to be a regressor if proj=True.

Moreover, even if the logic doesn't change, at predict time of the nuisance, we should always be clipping the conditional variance to be non-negative in this line:
https://github.com/py-why/EconML/blob/de4f05d95c59b39275a7f2780bcfe4ef20aa1b47/econml/iv/dr/_dr.py#L197

**Comment by kbattocchi** [comment]
@vsyrgkanis working through the math, it looks like all of E[(E[T|X,Z]-T)^2|X], E[(E[T|X,Z]-E[T|X])^2|X], and E[(E[T|X,Z]-E[T|X])(T-E[T|X])|X] are equal to Var(E[T|X,Z]|X) (but please correct me if I'm mistaken).

These are equivalent to training the variance model on (T_proj-T)^2, (T_proj-T_pred)^2, and (T_proj-T_pred)(T-T_pred) respectively.

It seems to me that the first of these would be noisier than the second but requires only that the projection model be well specified, while the second would be less noisy but requires both the projection and prediction models to be well-specified, and the third doesn't have any particular advantages that I can see.  Do you have any thoughts on which of these approaches to use?
