### ISSUE TITLE
Cannot install econml on mac m1 by poetry

### ISSUE THREAD

**Issue by luckem** [py-why/EconML#823]
Hi guys,

I've been trying to install econML using poetry on a Mac M1 but keeps getting error due to incompatible numpy requirements with shap 0.41. The shap issue has been solved in shap 0.42, so I believe releasing your current branch using shap 0.42 would fix that issue. Any chance you could release / pre-release in the coming days?

In a nutshell:

**Reproducing Code Example**
`poetry add econml`

**Error message**

```
Installing shap (0.41.0): Failed

IncompatibleConstraintsError

Incompatible constraints in requirements of oldest-supported-numpy (2022.11.19):
numpy (==1.22.2) ; platform_machine == "loongarch64" and python_version < "3.11"
numpy (==1.23.3) ; python_version == "3.9" and platform_system == "OS400"
numpy ; python_version >= "3.9" and platform_python_implementation == "PyPy"
```

**System Info**

```
Virtualenv
Python:         3.9.11
Implementation: CPython
Path:           /Users/m.lucke/Library/Caches/pypoetry/virtualenvs/test-Nag7r6NL-py3.9
Executable:     /Users/m.lucke/Library/Caches/pypoetry/virtualenvs/test-Nag7r6NL-py3.9/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.9.11
Path:       /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9
Executable: /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9
```

Additional remarks:
- `poetry add shap==0.41` fails but `poetry add shap==0.42` works fine, issue has been addressed in [v0.42](https://github.com/shap/shap/releases/tag/v0.42.0).
- Similar issues have been noticed with other packages such as scipy [here](https://github.com/scipy/scipy/issues/19437)

Thanks very much!

**Comment by luckem** [comment]
Ok so quick update, `poetry add econml` with 0.14.1 works fine after downgrading poetry from 1.6.1 to 1.5.1.
Closing the issue, as I am not sure whether there is anything you can address on your side in the short run.

**Comment by kbattocchi** [comment]
We have put out a beta (v0.15.0b1) of our next release, if you want to use it with more recent versions of shap.
