### ISSUE TITLE
CausalForestDML to get ate and ate confidence interval on training data

### ISSUE THREAD

**Issue by DailiZhang2010** [py-why/EconML#838]
There are two ways to do it:
1. use the est.ate_ and est.ate_stderr_.  Under the hood, it uses Doubly Robust ATE on training data
2. use est.ate(X=X, T0=T0, T1=T1) and est.ate_interval(X=X, T0=T0, T1=T1)

My target is to get the ate and confidence interval on the training data set. 

The question is: which one is more reliable?

Thanks for the great package and awesome documentation.

**Comment by fverac** [comment]
I would recommend ate_ for your use case, since you should get tighter confidence intervals. 

See more info here https://github.com/py-why/EconML/issues/753#issuecomment-1487537242

> This is expected; as you note the `ate_` attribute applies a double-robustness correction to the computation of the ATE itself (on the training data); the `ate()` method allows you to compute the ATE for any population by averaging the computed CATE values for each individual, so will not provide exactly the same result; however, if your use case is to compute the ATE for a data set that was not used in training then only the `ate()` method can be used for that.

**Comment by DailiZhang2010** [comment]
Thanks, @fverac
