### ISSUE TITLE
High dimensional categorical confounders (W) 

### ISSUE THREAD

**Issue by suryadipta** [py-why/EconML#847]
Hi,
I have a clarification question on how to use categorical variables taking a large number of unique values as confounders in the family of DML models. A simplified hypothetical view of my causal model is as follows:

`causal_graph = """
digraph {
catvar1 -> log_T; catvar1 -> log_Y; 
catvar2 -> log_T; catvar2 -> log_Y;
X_scaled -> log_Y;
catvar3 -> log_T; catvar3 -> log_Y;
catvar4 -> log_T; catvar4 -> log_Y;
log_T -> log_Y;
}
"""`

The following generates the causal graph that supports the assumptions that I am making:
`model = CausalModel(data=dd, 
                   graph=causal_graph,
                   treatment='log_T',
                   outcome='log_Y')`

In my case, the issue is that catvar1 is a high-cardinality variable taking around 1000 unique values. In the example to estimate price elasticity of orange juice in Sec. 4 (https://github.com/py-why/EconML/blob/main/notebooks/Double%20Machine%20Learning%20Examples.ipynb), the categorical variable 'brand' that takes only 3 distinct values has been converted to dummy variables, which have been subsequently used in the model. I was wondering if you can advise me the correct approach with my data and if any of the estimators (e.g. `SparseLinearDML` (?)) will take care of such high-dimensional categorical confounders automatically without having to use the get_dummies function. 

I have obtained the CATE estimates (together with confidence intervals) by using catvar1 through catvar4 as confounders in W without converting them to dummies, but only by using label encoding and converting them to numeric values, since that approach supports my causal graph (by using the CausalForest DML estimator), but I am not sure if that is the correct approach. 

So, the basic question is if a highly cardinal confounding variable can be used AS IS in estimating the nuisance regressions, for example when the nuisance regressions are using XGBoost, when log of quantity and log of price are the outcome and the treatment respectively, as in the example in sec. 4 (https://github.com/py-why/EconML/blob/main/notebooks/Double%20Machine%20Learning%20Examples.ipynb). 

Any thoughts/suggestions will be greatly appreciated! Thank you in advance!

**Comment by kbattocchi** [comment]
If you want to use your variable as a control (W), then as long as your first-stage nuisance models can deal with categoricals in this form (like XGBoost, as you mention), then this should be fine.

However, if you want to use your variable as a feature (X), meaning that the price elasticity can vary depending on the setting of that categorical variable, then for a model like CausalForestDML that should probably still be fine (because the final model fit on X is a forest-based non-parameteric model) but for models like LinearDML and SparseLinearDML you should one-hot-encode it (and drop one category, so that the columns are linearly independent), because those models fit treatment effect models that are linear in the numeric values in X.

**Comment by suryadipta** [comment]
Keith,
Thank you very much for the feedback!

**Comment by suryadipta** [comment]
Keith,
My basic question has been answered. I believe that we can close this issue. Thanking you and your team for your feedback and for this wonderful contribution to the community.

**Comment by jantacy** [comment]
Hi, @suryadipta 
I met the same problem, could you tell me how you solved it? thank you very much

**Comment by suryadipta** [comment]
Hi @jantacy,
I believe that using the tree based estimators (like XGBoost, Random Forests, or Causal Forests) make life easier in this situation. For instance, the CausalForestDML estimator in EconML can handle high-cardinality categorical variables directly when tree-based methods are used for nuisance regressions. It has been a while back but I think I used Label encoding along with the tree based methods (this was generating reasonable elasticity estimates for my case). However, it is not advisable to use label encoding if we are using linear models. I checked my results obtained via EconML with that obtained using the DoubleML package, and they were similar. In my experience, it is never a good idea to run the model with ~1000 dummy variables like those obtained via ohe; the model will probably never complete running and the results, if the model runs at all, will be suspect. 
Actually, if I go back to the work next time, I will experiment with using vector embedding techniques to cluster the categories into a handful of categories and then use them in the XGBoost model. Only a small number of the ~1000 categories have meaningful information about the target (or play a meaningful role in the relationship between treatment and target). Hence these should be reduced to a small number of meaningful categories. 
Hope you find this useful.

**Comment by jantacy** [comment]
@suryadipta thanks a lot，I tried like this: [https://github.com/py-why/EconML/blob/main/notebooks/Solutions/Causal%20Interpretation%20for%20Ames%20Housing%20Price.ipynb](Causal Interpretation for Ames Housing Price) maybe much the same as you said.
