### ISSUE TITLE
Inquiry About Confidence Interval Type in .effect_inference Method

### ISSUE THREAD

**Issue by lzy318** [py-why/EconML#903]
Hi EconML Team,

Thank you very much for developing such a fantastic and easy-to-use package. I have a question regarding the inference part of the package. When I use the command .effect_inference, for example, CausalForestDML.effect_inference, to obtain the confidence interval, is this confidence interval point-wise or simultaneous/uniform?

Thank you!

**Comment by vsyrgkanis** [comment]
Pointwise!

uniform intervals have only been established in the literature only three months ago!
https://arxiv.org/abs/2405.07860

hopefully these new methods will be incorporated at some point

**Comment by lzy318** [comment]
Cool! Thank you very much!

**Comment by lzy318** [comment]
Cool! Thank you very much!
