### ISSUE TITLE
CATE Estimation for with multiple features

### ISSUE THREAD

**Issue by vnwbd** [py-why/EconML#921]
Hi Team,

I would like to implement a DoubleML model for my specific use case, which involves user-level data consisting of over 100 features, a binary outcome, and a binary treatment feature.

Step 1: I plan to estimate the Conditional Average Treatment Effect (CATE) by focusing on just two key features. These features are essential as they define cohorts of similar customers among the dataset.

Step 2: In the second step, I aim to estimate the individual treatment effect at the user level. This will involve conditioning on all available features, as I need estimations for each individual user (each row of the data).

Could you please advise me on the appropriate functions to use for these two steps?

I would greatly appreciate any assistance you can provide!

Thank you!

**Comment by kbattocchi** [comment]
Both of these can in principle be estimated by any of our DML estimators by supplying the appropriate set of features as X (just the two for the "CATE", vs. all of them for the ITE) and putting the rest into W as controls.  However, note that to accurately learn the ITE with that many features you'd likely need either an very large number of rows or be willing to make some parametric assumptions (e.g. if you expect most features to have 0 effect, you could use SparseLinearDML).
